#!/bin/bash 

wget http://www.magentocommerce.com/downloads/assets/$MAGNETO_VERSION/magento-$MAGNETO_VERSION.tar.gz
tar -zxvf magento-$MAGNETO_VERSION.tar.gz
mv magento/* magento/.htaccess .
chmod -R o+w media var
chmod o+w app/etc
