#!/bin/bash
echo print contents 
tail -10 /etc/ssh/sshd_config
echo

echo append to ssh
sudo chmod 754 /etc/ssh/sshd_config
sudo echo "
Port 45454 
PermitRootLogin no 
AllowUsers david" >> sudo /etc/ssh/sshd_config
echo

echo print new contents 
tail -10 /etc/ssh/sshd_config
echo

echo add urser
sudo useradd david -p 123456
echo

echo all users
cat /etc/passwd
echo

echo restart ssh
sudo service ssh reload
echo
echo end

