#!/bin/bash
echo cd ~/.ssh/
cd ~/.ssh
echo

echo touch authorized_keys
touch authorized_keys
echo

echo touch authorized_keys
ls -a
echo

echo print contents 
tail -2 authorized_keys
echo

echo append to ssh
sudo chmod 754 authorized_keys
sudo echo $MY_KEY >> authorized_keys
echo

echo print new contents 
tail -2 authorized_keys
echo

echo end

