#!/bin/bash
echo cd ~/.ssh/
cd ~/.ssh
echo

echo who am i
whoami
echo

echo check config
cat /etc/ssh/sshd_config
echo

echo touch authorized_keys
touch authorized_keys
echo

echo print contents 
tail -2 authorized_keys
echo

echo append to ssh
sudo chmod 754 authorized_keys
sudo echo $MY_KEY >> authorized_keys
echo

echo chmod 600
sudo chmod 600 authorized_keys
echo

echo print new contents 
tail -2 authorized_keys
echo

echo end

